import type { NextPage } from "next";
import Head from "next/head";
import { Heading, Highlight, Text } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading>OnlyFood</Heading>
        <Text>Food is great!</Text>
      </main>
    </div>
  );
};

export default Home;
